[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[program:samba]
command=/usr/sbin/samba -F --no-process-group
autostart=true
autorestart=true
stderr_logfile=/var/log/samba-err.log
stdout_logfile=/var/log/samba-out.log
